require 'bundler'
Bundler.setup(:default)

require 'pry'
require 'yaml'
require 'atlas'
require 'virtus'

require_relative 'transformer/base'
require_relative 'transformer/attribute_validator'
require_relative 'transformer/dataset_cast'
require_relative 'transformer/caster'
require_relative 'transformer/caster/assumptions'
require_relative 'transformer/caster/shares'
require_relative 'transformer/caster/base'

require_relative 'transformer/caster/agriculture'
require_relative 'transformer/caster/agriculture/individual'
require_relative 'transformer/caster/agriculture/nulled'
require_relative 'transformer/caster/appliances'
require_relative 'transformer/caster/buildings'
require_relative 'transformer/caster/cooking'
require_relative 'transformer/caster/cooling'
require_relative 'transformer/caster/electricity_consumption'
require_relative 'transformer/caster/energy_sector'
require_relative 'transformer/caster/gas_consumption'
require_relative 'transformer/caster/heater'
require_relative 'transformer/caster/industry'
require_relative 'transformer/caster/industry/individual'
require_relative 'transformer/caster/industry/nulled'
require_relative 'transformer/caster/lighting'
require_relative 'transformer/caster/null_attributes'
require_relative 'transformer/caster/roof_surface_available_for_pv'
require_relative 'transformer/caster/space_heater'
require_relative 'transformer/caster/supply'
require_relative 'transformer/caster/to_atlas_attribute'
require_relative 'transformer/caster/transport'
require_relative 'transformer/caster/water_heater'
